create table Serveur(IDSer int not null primary key,NomSer varchar(20) not null,PreNomSer varchar(20) not null,login varchar(20) not null,password varchar(20) not null,actif varchar(1) not null,nbrRes int not null)
create table Tablee(NumTablee int not null primary key,NbrPlaceTablee int not null)
create table Reservation(CodeRes int not null primary key identity(1,1),DateRes datetime not null,NumTablee int not null,IDSer int not null)
create table Categorie(CodeCat varchar(2) not null primary key,LibelleCat varchar(20) not null)
create table Plate(CodePlat int not null primary key,NomPlate varchar(200) not  null,PrixPlate decimal,CodeCat varchar(2) not null)
create table QteReservee(CodeRes int not null,CodePlat int not null,Qte int not null)
create table logini(username varchar(20) not null primary key,password varchar(20) not null)

alter table Reservation add constraint fk1_Reservation foreign key (IDSer) references Serveur(IDSer)
alter table Reservation add constraint fk2_Reservation foreign key (NumTablee) references Tablee(NumTablee)
alter table Plate add constraint fk_Plate foreign key (CodeCat) references Categorie(CodeCat)
alter table QteReservee add constraint fk1_QteReservee foreign key (CodeRes) references Reservation(CodeRes)
alter table QteReservee add constraint fk2_QteReservee foreign key (CodePlat) references Plate(CodePlat)
alter table Serveur add constraint const_Serveur check (actif in ('+','-'))